<a href="https://colab.research.google.com/github/feguedes/Projetos-de-DS/blob/main/PROJETOCOVID.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style()
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv("https://raw.githubusercontent.com/feguedes/Projetos-de-DS/main/owid-covid-data.csv")

In [2]:
df.head()

  iso_code continent  ... human_development_index excess_mortality
0      AFG      Asia  ...                   0.511              NaN
1      AFG      Asia  ...                   0.511              NaN
2      AFG      Asia  ...                   0.511              NaN
3      AFG      Asia  ...                   0.511              NaN
4      AFG      Asia  ...                   0.511              NaN

[5 rows x 60 columns]

In [3]:
df.shape

(96208, 60)

In [5]:
df.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'new_vaccinations',
       'new_vaccinations_smoothed', 'total_vaccinations_per_hundred',
       'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
       'new_vaccinations_smoothed_per_million', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'excess_mortality'],
      dtype='object')

In [6]:
df.dtypes

iso_code                                  object
continent                                 object
location                                  object
date                                      object
total_cases                              float64
new_cases                                float64
new_cases_smoothed                       float64
total_deaths                             float64
new_deaths                               float64
new_deaths_smoothed                      float64
total_cases_per_million                  float64
new_cases_per_million                    float64
new_cases_smoothed_per_million           float64
total_deaths_per_million                 float64
new_deaths_per_million                   float64
new_deaths_smoothed_per_million          float64
reproduction_rate                        float64
icu_patients                             float64
icu_patients_per_million                 float64
hosp_patients                            float64
hosp_patients_per_million                float64
weekly_icu_admissions                    float64
weekly_icu_admissions_per_million        float64
weekly_hosp_admissions                   float64
weekly_hosp_admissions_per_million       float64
new_tests                                float64
total_tests                              float64
total_tests_per_thousand                 float64
new_tests_per_thousand                   float64
new_tests_smoothed                       float64
new_tests_smoothed_per_thousand          float64
positive_rate                            float64
tests_per_case                           float64
tests_units                               object
total_vaccinations                       float64
people_vaccinated                        float64
people_fully_vaccinated                  float64
new_vaccinations                         float64
new_vaccinations_smoothed                float64
total_vaccinations_per_hundred           float64
people_vaccinated_per_hundred            float64
people_fully_vaccinated_per_hundred      float64
new_vaccinations_smoothed_per_million    float64
stringency_index                         float64
population                               float64
population_density                       float64
median_age                               float64
aged_65_older                            float64
aged_70_older                            float64
gdp_per_capita                           float64
extreme_poverty                          float64
cardiovasc_death_rate                    float64
diabetes_prevalence                      float64
female_smokers                           float64
male_smokers                             float64
handwashing_facilities                   float64
hospital_beds_per_thousand               float64
life_expectancy                          float64
human_development_index                  float64
excess_mortality                         float64
dtype: object

In [7]:
df.date = pd.to_datetime(df.date)

In [8]:
(df.isnull().sum() / df.shape[0]).sort_values(ascending=False)

weekly_icu_admissions                    0.990916
weekly_icu_admissions_per_million        0.990916
weekly_hosp_admissions                   0.984315
weekly_hosp_admissions_per_million       0.984315
excess_mortality                         0.964598
icu_patients                             0.899728
icu_patients_per_million                 0.899728
people_fully_vaccinated_per_hundred      0.883752
people_fully_vaccinated                  0.883752
hosp_patients                            0.875364
hosp_patients_per_million                0.875364
new_vaccinations                         0.871674
people_vaccinated                        0.853900
people_vaccinated_per_hundred            0.853900
total_vaccinations_per_hundred           0.846323
total_vaccinations                       0.846323
new_vaccinations_smoothed_per_million    0.735022
new_vaccinations_smoothed                0.735022
total_tests                              0.552875
total_tests_per_thousand                 0.552875
new_tests_per_thousand                   0.549778
new_tests                                0.549778
handwashing_facilities                   0.548135
tests_per_case                           0.513013
positive_rate                            0.506787
new_tests_smoothed_per_thousand          0.477206
new_tests_smoothed                       0.477206
tests_units                              0.460253
extreme_poverty                          0.392920
male_smokers                             0.306638
female_smokers                           0.296337
reproduction_rate                        0.195337
hospital_beds_per_thousand               0.180463
stringency_index                         0.155590
total_deaths_per_million                 0.142940
new_deaths_per_million                   0.141319
total_deaths                             0.137920
new_deaths                               0.136298
aged_65_older                            0.114762
aged_70_older                            0.109637
median_age                               0.104679
gdp_per_capita                           0.101561
cardiovasc_death_rate                    0.100678
human_development_index                  0.099046
diabetes_prevalence                      0.078465
population_density                       0.070503
life_expectancy                          0.050391
new_deaths_smoothed_per_million          0.049331
new_cases_smoothed_per_million           0.049331
continent                                0.047127
new_deaths_smoothed                      0.044227
new_cases_smoothed                       0.044227
new_cases_per_million                    0.038885
total_cases_per_million                  0.038853
new_cases                                0.033729
total_cases                              0.033698
population                               0.006548
location                                 0.000000
date                                     0.000000
iso_code                                 0.000000
dtype: float64

In [17]:
df.loc[df.date == '2021-06-16'].sort_values(by='total_cases', ascending=False)
df.loc[df.date == '2021-06-16'].sort_values(by='total_deaths', ascending=False)

       iso_code      continent  ... human_development_index excess_mortality
94864  OWID_WRL            NaN  ...                   0.737              NaN
29449  OWID_EUR            NaN  ...                     NaN              NaN
80464  OWID_SAM            NaN  ...                     NaN              NaN
64046  OWID_NAM            NaN  ...                     NaN              NaN
5037   OWID_ASI            NaN  ...                     NaN              NaN
...         ...            ...  ...                     ...              ...
56654       FSM        Oceania  ...                   0.620              NaN
72894       KNA  North America  ...                   0.779              NaN
74025       WSM        Oceania  ...                   0.715              NaN
79029       SLB        Oceania  ...                   0.567              NaN
93296       VAT         Europe  ...                     NaN              NaN

[207 rows x 60 columns]

In [18]:
df_paises = df.loc[df.date == '2021-06-16'].sort_values(by='total_cases', ascending=False)

In [20]:
df_paises.head(15)

       iso_code      continent  ... human_development_index excess_mortality
94864  OWID_WRL            NaN  ...                   0.737              NaN
5037   OWID_ASI            NaN  ...                     NaN              NaN
29449  OWID_EUR            NaN  ...                     NaN              NaN
64046  OWID_NAM            NaN  ...                     NaN              NaN
91689       USA  North America  ...                   0.926              NaN
29960  OWID_EUN            NaN  ...                     NaN              NaN
80464  OWID_SAM            NaN  ...                     NaN              NaN
40287       IND           Asia  ...                   0.645              NaN
12722       BRA  South America  ...                   0.765              NaN
31685       FRA         Europe  ...                   0.901              NaN
89055       TUR           Asia  ...                   0.820              NaN
71893       RUS         Europe  ...                   0.824              NaN
968    OWID_AFR            NaN  ...                     NaN              NaN
91177       GBR         Europe  ...                   0.932              NaN
43825       ITA         Europe  ...                   0.892              NaN

[15 rows x 60 columns]

Total de casos:
* USA : 33.498.468
* BRA : 17.628.588
* FRA : 5.809.319
* TUR : 5.348.249
* RUS : 5.189.260

In [21]:
df_mortes = df.loc[df.date == '2021-06-16'].sort_values(by='total_deaths', ascending=False)

In [22]:
df_mortes.head(15)

       iso_code      continent  ... human_development_index excess_mortality
94864  OWID_WRL            NaN  ...                   0.737              NaN
29449  OWID_EUR            NaN  ...                     NaN              NaN
80464  OWID_SAM            NaN  ...                     NaN              NaN
64046  OWID_NAM            NaN  ...                     NaN              NaN
5037   OWID_ASI            NaN  ...                     NaN              NaN
29960  OWID_EUN            NaN  ...                     NaN              NaN
91689       USA  North America  ...                   0.926              NaN
12722       BRA  South America  ...                   0.765              NaN
40287       IND           Asia  ...                   0.645              NaN
56507       MEX  North America  ...                   0.779              NaN
68984       PER  South America  ...                   0.777              NaN
968    OWID_AFR            NaN  ...                     NaN              NaN
91177       GBR         Europe  ...                   0.932              NaN
43825       ITA         Europe  ...                   0.892              NaN
71893       RUS         Europe  ...                   0.824              NaN

[15 rows x 60 columns]

Total de mortes: 
* USA - 600.653
* BRA - 493.693
* IND - 381.903
* MEX - 230.624
* PER - 189.261